name: Second Workflow
on: workflow_dispatch
jobs:
  first-job: 
    runs-on: ubuntu-latest 
    steps:
      - name: Print Hello World
        run: |
              echo "hello world"
              sleep 5
      - name: Say Goodbye
        run: echo "Good bye"
